### ISSUE TITLE
Issue with running the example code

### ISSUE THREAD

**Issue by sivavayu** [gllmflndn/whisper.m#1]
This is my first issue creation on Git. I tried to run the example code with an audio file. I am encountering this error: 

**Unrecognized function or variable 'whisper_mex'.

Error in whisper (line 32)
            this.Context = whisper_mex('init',this.Model);**
            
I also failed to use make command after installing MSYS32 and MINGW64. 

```
$ make
make: *** No rule to make target 'whisper.cpp/ggml.c', needed by 'whisper.cpp/ggml.o'.  Stop.
```

I might be missing something very basic here. Please help.

**Comment by gllmflndn** [comment]
Hi @sivavayu I think the issue is that you need to [clone the git repository with submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules): `git clone --recurse-submodules`

In case you still have issues, here is a zip file containing a precompiled whisper_mex.mexw64: ~~whisper_mex.zip~~ (removed, see below)
This is not the most recent version and it might not run on your computer due to MATLAB/compiler differences but just in case.

**Comment by sivavayu** [comment]
@gllmflndn thank you for your response. 

I cloned the repository and tried the "make" command on the terminal. Not sure what's going wrong now. This is what I get: 

```
make
make -C whisper.cpp ggml.o
make[1]: Entering directory 'C:/Users/prane/Documents/GitHub/whisper.m/whisper.cpp'
/usr/bin/sh: line 1: cc: command not found
/usr/bin/sh: line 1: g++: command not found
I whisper.cpp build info:
I UNAME_S:  MINGW64_NT-10.0-19044
I UNAME_P:  unknown
I UNAME_M:  x86_64
I CFLAGS:   -I.              -O3 -DNDEBUG -std=c11   -fPIC -mfma -mf16c -mavx -mavx2
I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC
I LDFLAGS:
I CC:
I CXX:

cc  -I.              -O3 -DNDEBUG -std=c11   -fPIC -mfma -mf16c -mavx -mavx2   -c ggml.c -o ggml.o
process_begin: CreateProcess(NULL, cc -I. -O3 -DNDEBUG -std=c11 -fPIC -mfma -mf16c -mavx -mavx2 -c ggml.c -o ggm
l.o, ...) failed.
make (e=2): The system cannot find the file specified.
make[1]: *** [Makefile:182: ggml.o] Error 2
make[1]: Leaving directory 'C:/Users/prane/Documents/GitHub/whisper.m/whisper.cpp'
make: *** [Makefile:34: whisper.cpp/ggml.o] Error 2
```

So, I also tried the precompiled whisper_mex. And encounter these errors. 

> Incorrect number or types of inputs or outputs for function 'whisper_mex'.
> 
> Error in whisper (line 32)
>             this.Context = whisper_mex('init',this.Model);
> 
> Error in Code_v2 (line 17)
> w = whisper('small');

**Comment by gllmflndn** [comment]
Your MSYS installation does not seem to have MinGW-w64. Make sure to run this first:
```
pacman -Syu
pacman -Su
pacman -S --needed base-devel mingw-w64-x86_64-toolchain
```
From MATLAB, you might also have to do (assuming MSYS2 is installed in `C:\msys64\mingw64`):
```matlab
>> setenv('MW_MINGW64_LOC', 'C:\msys64\mingw64')
>> mex -setup
MEX configured to use 'MinGW64 Compiler (C)' for C language compilation.
```
and finally, before running `make`, set `PATH` appropriately in MSYS2:
```
PATH=/c/Program\ Files/MATLAB/R2018b/bin/win64:${PATH}
export MW_MINGW64_LOC=/c/msys64/mingw64/
PATH=/c/msys64/mingw64/bin/:${PATH}
```

I also upload here a new copy of the compiled mexw64 file: [whisper_mex.zip](https://github.com/gllmflndn/whisper.m/files/11180138/whisper_mex.zip)

**Comment by sivavayu** [comment]
@gllmflndn this worked great! I had installed MinGW-w64, but reinstalling through the pacman commands helped. I had to pick option 2 out of 18 options it showed after using the command: `pacman -S --needed base-devel mingw-w64-x86_64-toolchain`

I was able to compile and run it successfully. 

On a secondary note, is it possible to use Whisper for real-time streaming in Matlab?

**Comment by gllmflndn** [comment]
> On a secondary note, is it possible to use Whisper for real-time streaming in Matlab?

It would be possible to do something like [here](https://github.com/ggerganov/whisper.cpp/tree/master/examples/stream) but I think it would need some adjustments to the MEX interface (VAD detector, context tokens). As a starting point, have you tried running the [second example](https://github.com/gllmflndn/whisper.m#Usage) in a loop with short recording sessions?
